name: Build Kivy APK

on:
  push:
    branches:
      - main  # ou 'master' dependendo do nome do seu branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip zip unzip openjdk-17-jdk build-essential \
          git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
          libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
          zlib1g-dev libgstreamer1.0 libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
          libbz2-dev libsqlite3-dev libssl-dev libx11-dev libffi-dev \
          libncurses5 libstdc++6
        pip install --upgrade pip virtualenv cython
        pip install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: komen-apk
        path: bin/*.apk
